using System.Collections.Generic;
using System.IO;
using System.Linq;
using Features.CodeGeneratorModule.CustomCodeGeneratorModule.Scripts.Editor.Core;
using JetBrains.Annotations;
using UnityEditor;
using UnityEngine;
using Tools = IncrementalSourceGenerator.Utils.Tools;
namespace Features.SceneLoaderModule.Scripts {
    /// <summary>
    ///     Class for generated name of scene in built.
    /// </summary>
    [Generator, PublicAPI, HelpURL("https://github.com/AnnulusGames/UnityCodeGen")]
    public class SceneInBuiltGenerator : ICodeGenerator  {
        private const string SCENE_IN_BUILT = "SceneInBuilt";
        private const string TARGET_NAMESPACE = "Features.SceneLoaderModule.Scripts";
        public void Execute(GeneratorContext context) {
            string filePath = "Assets/" + TARGET_NAMESPACE.Replace(".", "/");
            context.OverrideFolderPath(filePath);

            IEnumerable<string> scenes = EditorBuildSettings.scenes.Select(sceneInBuild => Path.GetFileNameWithoutExtension(sceneInBuild.path))
                .Select(x => $"public const string {x.Replace(" ", string.Empty)} = \"{x}\";");

            string fields = string.Join("\n\t\t\t\t", scenes);
            var code = @$"// <auto-generated/>
#nullable enable

namespace {TARGET_NAMESPACE} {{
    public static class {SCENE_IN_BUILT} {{
        {fields}
    }}
}}";

            context.AddCode(Tools.BuildFileName(SCENE_IN_BUILT), code);
        }
    }
}